### ISSUE TITLE
Compilation difficulties

### ISSUE THREAD

**Issue by dejmail** [statgen/fastQValidator#13]
Hi there

Not being very good with c++ code, I was wondering how you would compile this program? I tried "make" and "g++ src/FastQValidator.cpp" but neither results in success. Any pointers would be much appreciated ?

Realised there is quite an extensive wiki, so let me go through that first.

**Comment by dejmail** [comment]
Seems it was just a problem on the server lacking a few files. Compiled file on my laptop.

**Comment by mktrost** [comment]
Great, glad you figured it out.  Let us know if you have any additional issues.
