### ISSUE TITLE
fastQValidator with *.fastq.gz files?

### ISSUE THREAD

**Issue by dastu** [statgen/fastQValidator#5]
Hi, I was trying to use fastQValidator with **gzipped** fastq files, but I am getting an error, see below. In the manual I read "Consumes gzipped and uncompressed text files transparently". Can you clarify?

```
$ ./fastQValidator --auto --file /home/dastu/BSSE_QGF_37905_C7HLCANXX_7/BSSE_QGF_37905_C7HLCANXX_7_C9_G04742_JFe_010915_GCTACGCT_TATCCTCT_S67_L007_R1_001.fastq.gz
BGZF EOF marker is missing in /home/dastu/BSSE_QGF_37905_C7HLCANXX_7/BSSE_QGF_37905_C7HLCANXX_7_C9_G04742_JFe_010915_GCTACGCT_TATCCTCT_S67_L007_R1_001.fastq.gz
ERROR: Failed to open file: /home/dastu/BSSE_QGF_37905_C7HLCANXX_7_C9_G04742_JFe_010915_GCTACGCT_TATCCTCT_S67_L007_R1_001.fastq.gz
Returning: 3 : FASTQ_OPEN_ERROR
```

**Comment by mktrost** [comment]
If I'm reading the error message correctly, it indicates that your gzipped file is actually a BGZF file that does not have the trailing EOF marker.  Is that what you expect?  If so, I can update fastQValidator to have an option to ignore the EOF check for BGZF files.  If that is not your situation, let me know, and I can see if I can figure out why the code thinks it is a BGZF file if it is not.

**Comment by dastu** [comment]
Indeed, it seems to be the BGZF compression that causes the problem. Older fastq.gz files don't result in the error. 
I found out together with our sequencing facility that the Illumina tool "bcl2fastq2" (which generates the fastq/fastq.gz files from the Illumina format) changed from GNU zip to BGFZ in one of the recent versions (see here: https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v216-Software-Guide-15051736-E.pdf). So all our data are going to be BGFZ compressed.

If you can easily modify fastQvalidator to accept these files, that would be great. I can also send you example files. Thanks a lot for your help.

**Comment by mktrost** [comment]
I updated fastQValidator to have a "--noeof" option to ignore a missing BGZF EOF check on BGZF files.  
I'm not familiar with bcl2fastq2, but I am surprised that it does not add those EOF indicators to the BGZF files it generates.  They help you to know a file hasn't been truncated.  But if you feel your FASTQ files are good, and you see the "BGZF EOF marker is missing" error message, just add "--noeof" on your command-line when running.

Let me know if you continue to have problems or if this fixes your issue.

**Comment by dastu** [comment]
works smoothly now with the file that gave the error message before. thanks a lot for update!

**Comment by golharam** [comment]
It would be nice to not have to add the --noeof option.  There is no way for us (the users) to know which compression algorithm was used.  If I used gzip -t, it reports the file is fine.
