### ISSUE TITLE
Unable to  install fastqvalidator

### ISSUE THREAD

**Issue by ChillarAnand** [statgen/fastQValidator#6]
Here is error  i am getting.

```
$ make clean
Makefile.inc:29: ../libStatGen/Makefiles/Makefile.tool: No such file or directory
Unable to locate: ./../libStatGen/Makefiles/Makefile.tool
To change the location, set LIB_PATH_GENERAL or LIB_PATH_FASTQ_VALIDATOR to the appropriate path to libStatGen. Or specify "make LIB_PATH_GENERAL=yourPath" or "make LIB_PATH_FASTQ_VALIDATOR=yourPath"
Use make cloneLib if you have git and want to clone the current libStatGen at that location.
make: *** No rule to make target `clean'.  Stop.
```

**Comment by mktrost** [comment]
Did you also install libStatGen (https://github.com/statgen/libStatGen)?
By default, the fastqvalidator looks for libStatGen to be installed in the same directory as fastqvalidator (up one directory from where you type make).  
If you have it installed someplace else, you can modify Makefile.inc to have the correct path to libStatGen.

**Comment by ChillarAnand** [comment]
:+1: 
Thanks @mktrost
